---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: authentication-viewer
rules:
- apiGroups:
  - config.openshift.io
  resources:
  - authentications
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: console-mce-authentication-viewer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: authentication-viewer
subjects:
- kind: ServiceAccount
  name: console-mce
  namespace: multicluster-engine